### ISSUE TITLE
cannot parse ©

### ISSUE THREAD

**Issue by hartshorne** [Mayank1791989/gql#4] opened 2017-04-21 17:45 UTC
obviously not a critical error, but spews a bunch of noise.

```
file: 'file:///.../file.tsx'
severity: 'Error'
message: 'Syntax Error: Cannot parse the unexpected character "\u2009".'
at: '1,5'
source: 'graphql'
```

**Comment by Mayank1791989** [comment] 2017-04-22 08:26
@hartshorne plz share the 'file.tsx' source and '.gqlconfig'.

**Comment by hartshorne** [comment] 2017-04-25 18:45
.gqlconfig:

```
{
  schema: {
    files: 'web/src/graphql/schema.graphql'
  },
  query: {
    files: [{
      match: 'web/src/**/*.ts*',
      parser: [
        'EmbeddedQueryParser',
        {
          startTag: 'gql`',
          endTag: '`'
        }
      ]
    }]
  }
}

```

file.tsx:

```
// © 2017

import { gql } from '../lib/graphql';

gql`
  fragment Account on Query {
    accounts {
      id
    }
  }
`;
```

problems:

```
file: 'file:///.../web/src/file.tsx'
severity: 'Error'
message: 'Syntax Error: Cannot parse the unexpected character "\u2009".'
at: '1,5'
source: 'graphql'
```

**Comment by Mayank1791989** [comment] 2017-04-26 17:46
the issue was due to Unicode thin space character between © and 2017 which you should not use in code as it's always hard to detect the presence, anyway pushed the fix **v2.2.4**

**Closed** 2017-04-26 17:51 UTC

**Comment by hartshorne** [comment] 2017-04-26 19:46
thanks!

**Comment by sandangel** [comment] 2017-11-17 09:26
![image](https://user-images.githubusercontent.com/22189661/32939989-a9b52dea-cbc4-11e7-8d12-2f01206c3bef.png)

.gqlconfig
{
   schema: {
     files: {
       include: 'apps/**/*.graphql'
     }
   },
   query: {
     files: [
       {
         match: 'apps/**/*.ts',
         parser: ['EmbeddedQueryParser', { startTag: 'gql`', endTag: '`' }]
       }
     ]
   }
}
I face this issue here. any idea?

**Comment by sandangel** [comment] 2017-11-17 09:30
![image](https://user-images.githubusercontent.com/22189661/32940126-281d0676-cbc5-11e7-83bb-d4d8018e0e9b.png)

I guess it because of this. When I hover it, the tooltip say that graphql language server has stop
I have installed watchman and @playlyfe/gql correctly. Have no idea why this happen

**Comment by sandangel** [comment] 2017-11-17 09:36
![image](https://user-images.githubusercontent.com/22189661/32940531-3d709352-cbc6-11e7-8d69-5eb4bc84eab9.png)
Here is log from output

**Comment by kumarharsh** [comment] 2017-11-17 11:09
The red icon comes in two scenaros:

1. When gql service has not started.
2. When gql service has tried to start, and failed. (See https://github.com/kumarharsh/graphql-for-vscode/issues/29). If this is the case, try shutting down the watchman server `watchman shutdown-server`, and then reload the vscode window (`Reload Window`) - this would start watchman again.

Also, please open a different issue for your problem. Discussing it here will make searching for it harder for future users.

**Comment by Mayank1791989** [comment] 2017-11-18 05:15
@sandangel Looks like the path to schema files is wrong that is why server not starting.

**Comment by sandangel** [comment] 2017-11-18 05:41
hmm..., the gql service is running now, but I still don't have syntax highlight with embedded schema,
here is my screenshot.
<img width="772" alt="screen shot 2017-11-18 at 14 40 23" src="https://user-images.githubusercontent.com/22189661/32977324-70a2a33e-cc6e-11e7-9c13-f357578751f0.png">

**Comment by Mayank1791989** [comment] 2017-11-18 05:47
@sandangel share output of graphql-for-vscode plugin. Is ide features working in above file?

**Comment by sandangel** [comment] 2017-11-18 06:13
<img width="826" alt="screen shot 2017-11-18 at 15 11 58" src="https://user-images.githubusercontent.com/22189661/32977559-e0def13a-cc72-11e7-9626-7dee3fb93e4b.png">

yeah, IDE features is working but gql plugin seem to be not

**Comment by Mayank1791989** [comment] 2017-11-18 06:24
vscode theme?

**Comment by sandangel** [comment] 2017-11-18 06:25
I use One Dark Italic Theme, I have also tried another theme but it just not work

**Comment by sandangel** [comment] 2017-11-18 07:03
I can confirm that when I add a schema file to project and hover the embedded string, it show the tooltips but there are still no syntax highlighting
<img width="2560" alt="screen shot 2017-11-18 at 15 59 23" src="https://user-images.githubusercontent.com/22189661/32977895-e178a1c0-cc79-11e7-8829-f8a647906f33.png">

**Comment by sandangel** [comment] 2017-11-18 07:08
wow I got it. That was because of Angular Component Extension plugin of onixie, after disable it, syntax highlighting worked. Thank you very much
